function(apply_project_warnings target WARN_AS_ERR)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if(WARN_AS_ERR)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(WARN_AS_ERR)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()

function(apply_sanitizers target ENABLE_ASAN ENABLE_UBSAN)
  if(NOT CMAKE_BUILD_TYPE MATCHES "Debug")
    return()
  endif()
  if(MSVC)
    return()
  endif()
  set(_flags "")
  if(ENABLE_ASAN)
    list(APPEND _flags -fsanitize=address)
  endif()
  if(ENABLE_UBSAN)
    list(APPEND _flags -fsanitize=undefined)
  endif()
  if(_flags)
    target_compile_options(${target} PRIVATE ${_flags})
    target_link_options(${target} PRIVATE ${_flags})
  endif()
endfunction()

